name: Microservices CI/CD

on:
  push:
    branches: [ main ] # Triggers on every push to main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven' # Speeds up future builds by caching dependencies


      - name: Build all services
        run: |
          mvn -f serv1/pom.xml clean package -DskipTests
          mvn -f serv2/pom.xml clean package -DskipTests
          mvn -f demo/pom.xml clean package -DskipTests

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Eureka Server
        uses: docker/build-push-action@v5
        with:
          context: ./serv1
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/eureka-server:latest

      - name: Build & Push Serv2
        uses: docker/build-push-action@v5
        with:
          context: ./serv2
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/serv2:latest

      - name: Build & Push Gateway
        uses: docker/build-push-action@v5
        with:
          context: ./demo
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/api-gateway:latest
